### PR TITLE
feat(exprimental): compact AnnData view

### PR DESCRIPTION
**Pull request by manzt**
Feel free to ignore...

On my flight home today, I poked around with a custom SVG representation of the AnnData "overview" object (rather than copying from the docs). It's a little more compact, but imporantly doesn't show the sizes of the related matrices. The depth of the stacks are currently also visible just by looking at the number in the metadata field below.

It seems to me the most useful information is to display `X` clearly (with n_vars/n_obs), but then all other dimensions are redundant and take up space. So this PR, just has a fixed size "handle" for hoving to view related tables.

### CODE REVIEW

**Comment by manzt** [comment]
@dwootton @thomcsmits 

https://github.com/manzt/anndata-repr/assets/24403730/e1d366f2-44cf-4d98-b997-71c63a5ba012

**Comment by cmdcolin** [comment]
dang that's awesome, it kinda looks like mine now but even better!

**Comment by thomcsmits** [comment]
This looks great!! I think it'd be good to be able to show the amount of layers still (happy to poke around with it), bit indeed much more compact! Nice work :)

**Comment by manzt** [comment]
feel free to poke! i won't have a chance to do more until next week

**Comment by manzt** [comment]
Ok, I was able to resolve both versions and merge conflicts. I'm going to merge this PR. To try it out:

```py
import pooch
import anndata
from anndata_repr import format_anndata_html_compact, format_anndata_html_complete

# download a dataset (or use your own)
datapath = pooch.retrieve(
    url="https://figshare.com/ndownloader/files/40067737",
    known_hash="md5:b80deb0997f96b45d06f19c694e46243",
    path="data",
    fname="scverse-getting-started-anndata-pbmc3k_processed.h5ad",
)

# both versions
variant_1 = format_anndata_html_complete
variant_2 = format_anndata_html_compact

# change next line to experiment with each variant
anndata.AnnData._repr_html_ = lambda self: variant_1(self)

adata = anndata.read_h5ad("../data/scverse-getting-started-anndata-pbmc3k_processed.h5ad")
adata
```

**Comment by thomcsmits** [comment]
Really like the variant_1 and variant_2! One note that on variant_1, layers/X is not clickable right now. We can just use the same logic as you changed for variant_2, with only the graphic as a difference. But perhaps we can first see what the scverse core says

**Comment by manzt** [comment]
> Really like the option to select variant_1 and variant_2! One note that on variant_1

Agreed. I think this is good for iterating right now, but I do think we should try to settle on something. Maintaining multiple implementations will be much more challenging than one, and I think we should (with input from scverse) narrow in on one implementation.

> One note that on variant_1, layers/X is not clickable right now. 

This is consistent with the behavior before this PR.

**Pull request merged**
